// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Script.sol";
import {DelegatedWallet} from "../src/Firstdraft.sol";

interface IERC20 {
    function approve(address spender, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
}

contract ExecuteBatchSwap is Script {
    // Use the user address directly since EIP-7702 stores state there
    DelegatedWallet constant WALLET =
        DelegatedWallet(payable(0xa11cCD98850c568eA86d964dabE7afeB085b7DFe));

    // User credentials (for signing the batch order)
    address constant USER = 0xa11cCD98850c568eA86d964dabE7afeB085b7DFe;
    uint256 constant USER_PK =
        0xf1b6c516f9431ff5b74fe0deee6c768c2bac756e3d0e5321f65ab6607a162cb9;

    // Implementation contract address for EIP-7702 (new contract with batch swaps)
    address constant IMPLEMENTATION_ADDRESS =
        0x6B90FAF6d634EDE2E56c024A9b852A9607a5c7bf;

    // Token addresses on Optimism
    address constant USDC = 0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85; // USDC on Optimism
    address constant ONEINCH = 0xAd42D013ac31486B73b6b059e748172994736426; // 1INCH on Optimism

    // 1inch Router on Optimism (v5)
    address constant ONEINCH_ROUTER =
        0x111111125421cA6dc452d289314280a0f8842A65;

    function run() external {
        vm.startBroadcast(USER_PK);

        console.log("=== EXECUTING BATCH SWAP (2 PARTS WITH 1 SIGNATURE) ===");
        console.log("Wallet Address:", address(WALLET));
        console.log("User:", USER);

        // Use EIP-7702 delegation
        console.log("\nSetting up EIP-7702 delegation...");
        vm.signAndAttachDelegation(IMPLEMENTATION_ADDRESS, USER_PK);

        // Check initial balances
        uint256 usdcBalanceBefore = IERC20(USDC).balanceOf(address(WALLET));
        uint256 oneinchBalanceBefore = IERC20(ONEINCH).balanceOf(
            address(WALLET)
        );

        console.log("\nInitial Balances:");
        console.log("- USDC:", usdcBalanceBefore);
        console.log("- 1INCH:", oneinchBalanceBefore);

        // Create batch swap order parameters
        uint256 currentTime = block.timestamp;
        uint256 totalAmountOut = 200000; // 0.2 USDC total (will be split into 4 parts of 0.05 each)
        uint256 batchParts = 4;
        uint256 minTimeBetweenExecutions = 5; // 5 seconds between executions

        DelegatedWallet.BatchSwapOrder memory batchOrder = DelegatedWallet
            .BatchSwapOrder({
                tokenOut: USDC, // Selling USDC
                tokenIn: ONEINCH, // Buying 1INCH
                totalAmountOut: totalAmountOut,
                minAmountInPerPart: 0.01 ether, // Minimum 1INCH per part (reduced for smaller parts)
                timestamp: currentTime,
                expiration: currentTime + 1 hours, // Order expires in 1 hour
                orderHash: bytes32(0), // Will be generated by the contract
                batchParts: batchParts,
                minTimeBetweenExecutions: minTimeBetweenExecutions,
                maxPriceDeviation: 500, // 5% max price deviation
                executorTipBps: 10, // 0.1% tip for executors
                // Dutch auction parameters (no premium for this demo)
                startPremiumBps: 0,
                decayRateBps: 0,
                decayInterval: 60
            });

        console.log("\nBatch Swap Order Parameters:");
        console.log("- Total Amount Out:", totalAmountOut, "(0.2 USDC total)");
        console.log("- Batch Parts:", batchParts, "(0.05 USDC each)");
        console.log(
            "- Min Time Between Executions:",
            minTimeBetweenExecutions,
            "seconds"
        );
        console.log(
            "- Max Price Deviation:",
            batchOrder.maxPriceDeviation,
            "bps (5%)"
        );

        // Create user signature for the batch swap order
        // Note: We need to generate the order hash first
        bytes32 orderHash = keccak256(
            abi.encode(
                batchOrder.tokenOut,
                batchOrder.tokenIn,
                batchOrder.totalAmountOut,
                batchOrder.minAmountInPerPart,
                batchOrder.timestamp,
                batchOrder.expiration,
                batchOrder.batchParts,
                batchOrder.minTimeBetweenExecutions,
                batchOrder.maxPriceDeviation,
                batchOrder.executorTipBps,
                batchOrder.startPremiumBps,
                batchOrder.decayRateBps,
                batchOrder.decayInterval,
                block.chainid,
                address(WALLET)
            )
        );

        bytes32 messageHash = keccak256(
            abi.encodePacked("\x19Ethereum Signed Message:\n32", orderHash)
        );

        (uint8 v, bytes32 r, bytes32 s) = vm.sign(USER_PK, messageHash);
        bytes memory userSig = abi.encodePacked(r, s, v);

        console.log("\nRegistering batch swap order...");
        console.log("- Order Hash:", vm.toString(orderHash));

        try WALLET.registerBatchSwapOrder(batchOrder, userSig) returns (
            bytes32 registeredOrderHash
        ) {
            console.log("\n[SUCCESS] Batch swap order registered!");
            console.log(
                "- Registered Order Hash:",
                vm.toString(registeredOrderHash)
            );

            // Verify the registration
            (
                DelegatedWallet.BatchSwapOrder memory order,
                uint256 executedParts,
                uint256 nextExecutionTime,
                bool isComplete,
                bool isCancelled
            ) = WALLET.getBatchSwapStatus(registeredOrderHash);

            console.log("\nBatch Order Status:");
            console.log(
                "- Executed Parts:",
                executedParts,
                "/",
                order.batchParts
            );
            console.log("- Is Complete:", isComplete);
            console.log("- Is Cancelled:", isCancelled);
            console.log("- Next Execution Time:", nextExecutionTime);

            // Execute all 4 parts with timing
            for (uint256 i = 0; i < batchParts; i++) {
                console.log("\n=== EXECUTING PART", i + 1, "===");
                _executeBatchPart(
                    registeredOrderHash,
                    i,
                    string(abi.encodePacked("Part ", vm.toString(i + 1)))
                );

                // Wait for next execution window (except for last part)
                if (i < batchParts - 1) {
                    console.log("\n=== WAITING FOR NEXT EXECUTION WINDOW ===");
                    vm.warp(block.timestamp + minTimeBetweenExecutions + 1);
                    console.log(
                        "- Warped time forward by",
                        minTimeBetweenExecutions + 1,
                        "seconds"
                    );
                }
            }

            // Check final status
            (, uint256 finalExecutedParts, , bool finalIsComplete, ) = WALLET
                .getBatchSwapStatus(registeredOrderHash);

            console.log("\n=== BATCH SWAP COMPLETED ===");
            console.log(
                "- Final Executed Parts:",
                finalExecutedParts,
                "/",
                batchParts
            );
            console.log("- Is Complete:", finalIsComplete);

            // Check final balances
            uint256 usdcBalanceAfter = IERC20(USDC).balanceOf(address(WALLET));
            uint256 oneinchBalanceAfter = IERC20(ONEINCH).balanceOf(
                address(WALLET)
            );

            console.log("\nFinal Balances:");
            console.log("- USDC before:", usdcBalanceBefore);
            console.log("- USDC after:", usdcBalanceAfter);
            console.log("- USDC used:", usdcBalanceBefore - usdcBalanceAfter);
            console.log("- 1INCH before:", oneinchBalanceBefore);
            console.log("- 1INCH after:", oneinchBalanceAfter);
            console.log(
                "- 1INCH gained:",
                oneinchBalanceAfter - oneinchBalanceBefore
            );

            console.log("\nSUCCESS: Executed 4 swaps with proper timing!");
        } catch Error(string memory reason) {
            console.log("\n[ERROR] Batch order registration failed:", reason);
        } catch (bytes memory lowLevelData) {
            console.log(
                "\n[ERROR] Batch order registration failed with low-level error"
            );
            console.logBytes(lowLevelData);
        }

        vm.stopBroadcast();
    }

    function _executeBatchPart(
        bytes32 orderHash,
        uint256 partIndex,
        string memory partName
    ) internal {
        console.log("Executing", partName, "part...");

        // Fetch fresh 1inch swap data using FFI
        console.log("- Fetching fresh 1inch swap data...");
        string[] memory inputs = new string[](3);
        inputs[0] = "node";
        inputs[1] = "fetchBatch1inch.js"; // Use the batch-specific fetch script
        inputs[2] = "--ffi";

        bytes memory res = vm.ffi(inputs);
        string memory output = string(res);

        // Parse the output (format: hexData|dstAmount)
        bytes memory swapData;
        uint256 expectedAmount;

        // Find the pipe character
        bytes memory outputBytes = bytes(output);
        uint256 pipeIndex = 0;
        for (uint256 i = 0; i < outputBytes.length; i++) {
            if (outputBytes[i] == "|") {
                pipeIndex = i;
                break;
            }
        }

        if (
            pipeIndex == 0 ||
            bytes(output).length == 0 ||
            keccak256(bytes(output)) == keccak256(bytes("ERROR"))
        ) {
            console.log(
                "- [WARNING] Failed to fetch 1inch data, using fallback"
            );
            // Use fallback data for demo
            swapData = hex"1234"; // Placeholder
            expectedAmount = 0.3 ether; // Fallback amount
        } else {
            // Extract hex data and expected amount
            bytes memory hexBytes = new bytes(pipeIndex);
            for (uint256 i = 0; i < pipeIndex; i++) {
                hexBytes[i] = outputBytes[i];
            }

            // Convert hex string to bytes
            swapData = vm.parseBytes(string(hexBytes));

            // Extract expected amount
            bytes memory amountBytes = new bytes(
                outputBytes.length - pipeIndex - 1
            );
            for (uint256 i = pipeIndex + 1; i < outputBytes.length; i++) {
                amountBytes[i - pipeIndex - 1] = outputBytes[i];
            }
            expectedAmount = vm.parseUint(string(amountBytes));
        }

        console.log("- Expected 1INCH output:", expectedAmount);
        console.log("- Swap data length:", swapData.length);

        // Create the swap call
        DelegatedWallet.Call memory swapCall = DelegatedWallet.Call({
            to: ONEINCH_ROUTER,
            value: 0,
            data: swapData
        });

        // Calculate current price (simplified)
        uint256 currentPrice = expectedAmount > 0
            ? (200000 * 1e18) / expectedAmount
            : 3000 * 1e18;

        console.log("- Current price:", currentPrice);
        console.log("- Executing batch part", partIndex, "...");

        try
            WALLET.executeBatchSwapPart(orderHash, swapCall, currentPrice)
        returns (bytes memory result) {
            console.log("- [SUCCESS]", partName, "part executed!");
        } catch Error(string memory reason) {
            console.log(
                "- [ERROR]",
                partName,
                "part execution failed:",
                reason
            );
        } catch (bytes memory lowLevelData) {
            console.log(
                "- [ERROR]",
                partName,
                "part failed with low-level error"
            );
            console.logBytes(lowLevelData);
        }
    }
}
